modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT License"

[[mods]]
modId = "backpackdisplay"
version = "${version}"
displayName = "Backpack Display"
authors = "Blue_Beaker"
description = '''
Shows what's in your backpack!
'''
logoFile = "icon.png"

[[dependencies.backpackdisplay]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backpackdisplay]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backpackdisplay]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backpackdisplay]]
modId = "crafttweaker"
mandatory = false
versionRange = "[14.0.44,)"
ordering = "AFTER"
side = "BOTH"