@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.bluebeaker.backpackdisplay.api;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;