@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package io.bluebeaker.backpackdisplay.api;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;