@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.bluebeaker.backpackdisplay.displayslot;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;