@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.bluebeaker.backpackdisplay.fabric;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;