@FieldsAreNonnullByDefault
@MethodsReturnNonnullByDefault
package io.bluebeaker.backpackdisplay.utils;

import net.minecraft.FieldsAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;